title: Informoji
description: Emoji and Unicode information
show_downloads: false
theme: jekyll-theme-dinky
navbar-links:
  Twitter: "http://twitter.com/Informoji"
  Github: "http://github.com/Crissov/informoji/"

author:
  name: Christoph Päper
  email: "informoji@crissov.de"
  github: Crissov
  twitter: Informoji
#  twitter: Cr1ss0v
  stackoverflow: "3002699/crissov"
  stackexchange: "3589744/crissov"

permalink: /:category/:title
